// examples/vue/src/App.vue
<template>
  <div id="app">
    <header class="app-header">
      <h1>AngusEditor - Vue 3 Example</h1>
      <p>A feature-rich text editor with light and dark themes</p>
    </header>

    <main class="app-main">
      <AngusEditor
        v-model="content"
        :theme="theme"
        @update:theme="theme = $event"
        placeholder="Start writing your amazing content..."
        :showToolbar="true"
        :showFooter="true"
      />

      <div class="output-section">
        <h2>HTML Output</h2>
        <pre>{{ content }}</pre>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { AngusEditor } from '@angus-editor/vue';

const theme = ref<'light' | 'dark'>('light');
const content = ref(`
  <h1>Welcome to AngusEditor!</h1>
  <p>This is a powerful rich text editor built with Vue 3 and Tiptap.</p>
  <h2>Features</h2>
  <ul>
    <li>Rich text formatting (bold, italic, underline, etc.)</li>
    <li>Headings and paragraphs</li>
    <li>Lists (ordered, unordered, and task lists)</li>
    <li>Tables</li>
    <li>Images and links</li>
    <li>Code blocks</li>
    <li>Light and dark themes</li>
  </ul>
  <h2>Try It Out</h2>
  <p>Feel free to edit this text and explore all the features!</p>
`);
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  min-height: 100vh;
  padding: 20px;
}

#app {
  max-width: 1200px;
  margin: 0 auto;
}

.app-header {
  text-align: center;
  color: white;
  margin-bottom: 40px;
}

.app-header h1 {
  font-size: 3em;
  margin-bottom: 10px;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.app-header p {
  font-size: 1.2em;
  opacity: 0.9;
}

.app-main {
  background: white;
  border-radius: 12px;
  padding: 30px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.output-section {
  margin-top: 30px;
  padding: 20px;
  background: #f5f5f5;
  border-radius: 8px;
}

.output-section h2 {
  margin-bottom: 10px;
  color: #333;
}

.output-section pre {
  white-space: pre-wrap;
  word-wrap: break-word;
  font-family: 'Courier New', monospace;
  font-size: 12px;
  color: #666;
  max-height: 300px;
  overflow-y: auto;
}

@media (max-width: 768px) {
  body {
    padding: 10px;
  }

  .app-header h1 {
    font-size: 2em;
  }

  .app-main {
    padding: 15px;
  }
}
</style>

// examples/react/src/App.tsx
import React, { useState } from 'react';
import { AngusEditor } from '@angus-editor/react';
import './App.css';

function App() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  const [content, setContent] = useState(`
    <h1>Welcome to AngusEditor!</h1>
    <p>This is a powerful rich text editor built with React and Tiptap.</p>
    <h2>Features</h2>
    <ul>
      <li>Rich text formatting (bold, italic, underline, etc.)</li>
      <li>Headings and paragraphs</li>
      <li>Lists (ordered, unordered, and task lists)</li>
      <li>Tables</li>
      <li>Images and links</li>
      <li>Code blocks</li>
      <li>Light and dark themes</li>
    </ul>
    <h2>Try It Out</h2>
    <p>Feel free to edit this text and explore all the features!</p>
  `);

  return (
    <div id="app">
      <header className="app-header">
        <h1>AngusEditor - React Example</h1>
        <p>A feature-rich text editor with light and dark themes</p>
      </header>

      <main className="app-main">
        <AngusEditor
          content={content}
          theme={theme}
          onUpdate={setContent}
          onThemeChange={setTheme}
          placeholder="Start writing your amazing content..."
          showToolbar={true}
          showFooter={true}
        />

        <div className="output-section">
          <h2>HTML Output</h2>
          <pre>{content}</pre>
        </div>
      </main>
    </div>
  );
}

export default App;
